### ISSUE TITLE
Changes are required for the Meson build file

### ISSUE THREAD

**Issue by Basile-z** [libmir/mir-core#11]
> Dependency mir-core from subproject subprojects/mir-core found: YES
subprojects/mir-core/meson.build:40: DEPRECATION: Library mir-core was passed to the "libraries" keyword argument of a previous call to generate() method instead of first positional argument. Adding mir-core to "Requires" field, but this is a deprecated behaviour that will change in a future version of Meson. Please report the issue if this warning cannot be avoided in your case.

[log file](https://travis-ci.org/dlang-community/stdx-allocator/jobs/519936328#L641)

Maybe in other Mir libraries too.

**Comment by 9il** [comment]
fixed
