### ISSUE TITLE
Documentation for fastmath/optmath out of date

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-core#15]
It looks like the documentation for fastmath and optmath make reference to 'unsafe-fp-math', but that is not part of the code. 

The documentation for fastmath says 
```
Functions attribute, an alias for `ldc.attributes.fastmath = AliasSeq!(llvmAttr("unsafe-fp-math", "true"), llvmFastMathFlag("fast"))` .
```
but the code is actually
```
alias fastmath = ldc.attributes.fastmath;
```

The documentation for optmath says
```
Functions attribute, an alias for `AliasSeq!(llvmAttr("unsafe-fp-math", "false"), llvmFastMathFlag("fast"))`
```
but the code is actually
```
alias optmath = AliasSeq!(ldc.attributes.llvmFastMathFlag("fast"));
```

**Comment by 9il** [comment]
fixed, http://mir-core.libmir.org/mir_math_common.html
