### ISSUE TITLE
Improve error messages for mir.math.common functions

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-core#20]
The error messages for `mir.math.common` functions are not good when passing in integer values. This is because `mir.internal.utliity.isFloatingPoint` is true for integer types. So the integer type is passed to it, but then there is an error that it does not match a phobos function. 

Another option is to take the current `isFloatingPoint` and making them new functions, as in `isConvertibleToFloatingPoint` and then having the existing `isFloatingPoint` implemented more as in the phobos implementation. 

```
/+dub.sdl:
dependency "mir-core" version="*"
+/
import std.stdio;
import mir.internal.utility: isFloatingPoint;
import mir.math.common: sqrt;

void main() {
    int x = 9;
    static assert(isFloatingPoint!(typeof(x))); //passes without issue
    auto y = sqrt(x);
}
```
The error message I get on `run.dlang.org` is
```
onlineapp.d(13,18): Error: `mir.math.common.sqrt` called with argument types `(int)` matches both:
/dlang/dmd/linux/bin64/../../src/phobos/std/math.d(2106,7):     `std.math.sqrt(float x)`
and:
/dlang/dmd/linux/bin64/../../src/phobos/std/math.d(2112,6):     `std.math.sqrt(real x)`
dmd failed with exit code 1.
```

**Comment by 9il** [comment]
`isFloatingPoint` is fixed in `v1.1.6`

**Comment by jmh530** [comment]
Will this break functions like ‘gmean’ for   types that convert to floating
point?

**Comment by 9il** [comment]
> Will this break functions like ‘gmean’ for types that convert to floating point?

Potentially it can break something.

**Comment by 9il** [comment]
Current `mir-algorithm` master passes tests.

**Comment by jmh530** [comment]
Yes, but I haven’t added ‘gmean’ or switched ‘mean’ to only work for
floating point.

**Comment by 9il** [comment]
`mean` can work with integer arrays, but it should return a `double` anyway.
