### ISSUE TITLE
Should `shape` handle multidimensional arrays?

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-core#21]
I was surprised that the following UT passes with `mir.primitives`. Is this the intended behavior or should it also handle multidimensional dynamic arrays? 

The current implementation implies that the `elementCount` of a multidimensional array is equal to its length.

```
version(mir_test)
@safe pure nothrow
unittest
{
    static assert([[1, 2, 3], [4, 5 ,6]].shape == [2]);
}
```

**Comment by 9il** [comment]
Yes, this is the intended behavior.
A `shape` from the http://mir-algorithm.libmir.org/mir_ndslice_allocation.html#.shape
that has two arguments will return a deep variant of a shape.
