### ISSUE TITLE
mir.conv: to does not support enum

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-core#22]
The UT below fails because `mir.conv`'s `to` function does not support enums. The line in `mir.conv` that causes the error is `return cast(T) args[0];`, which is .

By contrast, this would pass with `std.conv`'s `to` function, but you have to remove `nothrow @nogc`. 

```
@safe pure nothrow @nogc
unittest
{
    enum Foo
    {
        A,
        B,
        C
    }

    import mir.conv: to;

    Foo foo = Foo.A;
    auto x = to!Foo("A");
    assert(x == foo);
}
```

**Comment by 9il** [comment]
`v1.1.8`, it is `@nogc` but throws an exception
