### ISSUE TITLE
README says "no runtime dependency" but many core modules are imported

### ISSUE THREAD

**Issue by joseph-wakeling-frequenz** [libmir/mir-core#23]
In the current master branch the following `core` modules are imported:

```
source/mir/bitmanip.d:595:    import core.exception : AssertError;
source/mir/bitop.d:320:    import core.bitop: popcnt;
source/mir/bitop.d:343:    import core.bitop: bsr;
source/mir/bitop.d:394:    import core.bitop: bsf;
source/mir/checkedint.d:34:    public import core.checkedint : adds, addu, subs, subu, muls, mulu, negs;
source/mir/conv.d:9:public import core.lifetime: emplace;
source/mir/conv.d:116:            import core.stdc.string : memset;
source/mir/conv.d:132:            import core.stdc.string : memset;
source/mir/conv.d:138:            import core.stdc.string : memset;
source/mir/conv.d:215:        import core.internal.lifetime: emplaceRef;
source/mir/conv.d:223:    import core.lifetime: forward;
source/mir/functional.d:52:public import core.lifetime : forward;
source/mir/internal/memory.d:80:            import core.stdc.string : memcpy;
source/mir/internal/memory.d:131:    import core.stdc.errno : ENOMEM, EINVAL;
source/mir/math/common.d:296:    static import core.stdc.math;
source/mir/math/common.d:438:    static import core.stdc.math;
source/mir/math/ieee.d:640:        import core.checkedint: addu;
source/mir/math/ieee.d:944:        import core.math: ldexp;
source/mir/math/ieee.d:954:                import core.math: ldexp;
```

While obviously these are fairly low-level dependencies (it's not relying on the full runtime), this usage does appear to contradict the README.  It might be a good idea to explain this more clearly.  Assuming that policy has changed, it might also be a good idea to make clear to developers which `core` modules are acceptable and which not.

**Comment by 9il** [comment]
updated. Also, it isn't a problem to import something. You can import C headers or generics that don't have a runtime (linking) dependencies. I have updated the readme. It should be 100% betterC compatible when compiled with LDC in release mode. Most of thing should work with LDC and BetterC mode in debug mode if compiled with -betterC.

**Comment by 9il** [comment]
If you have some runtime linking dependencies from Phobos when use mir-core and compile with LDC (debug or relase) please open an issue, we can tag a new release soon.
