### ISSUE TITLE
Feature request: Variant.trustedGet multiple values

### ISSUE THREAD

**Issue by andre2007** [libmir/mir-core#33]
I have a scenario like this:

There are 2 FMU classes version 1 and two FMU classes version 2.
Version 1 supports a method initialize, while this method is not available in version 2.

I want to call trustedGet like this `fmu.trustedGet!(FMU1Slave, FMU1Model).initialize();`.
At the specific code line, I know fmu is either FMU1Slave  or FMU1Model. Both classes
supports method `initialize`. It should call method `initialize` independent whether it is now FMU1Slave or FMU1Model.

``` d
/+ dub.sdl:
	name "app"
	dependency "mir-core" version="1.1.51"
+/

import mir.algebraic;

class FMU1Slave
{
	void instantiate() {}
	void initialize() {}
}

class FMU1Model
{
	void instantiate() {}
	void initialize() {}
}

class FMU2Slave
{
	void instantiate() {}
	void enterInitializationMode() {}
	void exitInitializationMode() {}
}

class FMU2Model
{
	void instantiate() {}
	void enterInitializationMode() {}
	void exitInitializationMode() {}
}

void main()
{

	Variant!(FMU1Slave, FMU1Model, FMU2Slave, FMU2Model) fmu;
	string fmiVersion;
	bool isCoSimulation;

    if (fmiVersion == "1.0")
    {
        if (isCoSimulation)
            fmu = new FMU1Slave();
        else
            fmu = new FMU1Model();
        fmu.instantiate();
        fmu.trustedGet!(FMU1Slave, FMU1Model).initialize();
    }
    else
    {
        if (isCoSimulation)
            fmu = new FMU2Slave();
        else
            fmu = new FMU2Model();
        fmu.instantiate();
        fmu.enterInitializationMode();
        fmu.exitInitializationMode();
    }
}
```

**Comment by 9il** [comment]
Yes, we already have a draft for it. Will be added.

**Comment by 9il** [comment]
Overload to work with algebraic type sets.
 - [trustedGet](http://mir-core.libmir.org/mir_algebraic.html#.Algebraic.trustedGet)
 - [get](http://mir-core.libmir.org/mir_algebraic.html#.Algebraic.get.3)
 - [constructor](http://mir-core.libmir.org/mir_algebraic.html#.Algebraic.this)

@deviator this may be helpful for the #34

**Comment by 9il** [comment]
v1.1.56

**Comment by andre2007** [comment]
@9il thank you
