### ISSUE TITLE
Preference of conversion to `bool` over `long` for `int` literals

### ISSUE THREAD

**Issue by nordlow** [libmir/mir-core#45]
Because of Walter Bright's strong preference for implicit conversion to bool (over integer) the following currently holds:

```d
    import mir.algebraic : Variant;
    assert(Variant!(bool, double)(3.14).toString == "3.14");
    assert(Variant!(bool, int)(1).toString == "1");
    assert(Variant!(bool, long)(1L).toString == "1");
    assert(Variant!(bool, long)(1).toString == "true"); // unsound?
    assert(Variant!(long, bool)(1).toString == "true"); // unsound?
```

I believe the last two asserts instead should pass as

```d
    assert(Variant!(bool, long)(1).toString == "1");
    assert(Variant!(long, bool)(1).toString == "1");
```

**Comment by 9il** [comment]
We can add a workaround, thought.

**Comment by nordlow** [comment]
Thanks!

**Comment by nordlow** [comment]
I can't see a test added.

**Comment by nordlow** [comment]
If I want to make use of 1.1.76 and I only have

```sdl
dependency "mir-ion" version="~>0.1.48"
```

in my dub.sdl should I replace that line with

```sdl
dependency "mir-core" version="~>1.1.76"
dependency "mir-ion" version="~>0.1.48"
```

?

**Comment by 9il** [comment]
> I can't see a test added.

I have modified existing one.

> Do you have to bump mir-ion's dependency on mir-core aswell?

No. One can update dub.selections.json, no need to change dub.sdl.

**Comment by nordlow** [comment]
Thanks.
