### ISSUE TITLE
Incompatible with all recent versions of GDC

### ISSUE THREAD

**Issue by hatf0** [libmir/mir-core#46]
```
 ../../../.dub/packages/mir-core-1.1.76/mir-core/source/mir/functional.d:48:15: error: module lifetime is in file 'core/lifetime.d' which cannot be read
   48 | public import core.lifetime : forward;
```

This is because GDC 10/11 is stuck on a version freeze to v2.076 (according to ibuclaw), whereas this move was introduced in v2.085 (where `std.functional.forward` was moved to `core.lifetime`).

**Comment by 9il** [comment]
We aren't going to support GDC at least until it gets faster FE updates.
