### ISSUE TITLE
`mir.math.common.round` impure on windows

### ISSUE THREAD

**Issue by rjkilpatrick** [libmir/mir-core#47]
As strange as it sounds, only on Windows, `mir.math.common.round` is impure. On Linux and macOS however, it's pure.

Below is a minimal working example:

```d
pure unittest {
    import mir.math.common;
    cast(void) 2.0f.round; // discard result so that the function is pure
}

void main(){}
```

Running `dub test -q` gives the following trace on windows.

```
source\app.d(3,13): Error: `pure` function `app.round` cannot call impure function `mir.math.common.round!float.round`
C:\D\dmd2\windows\bin64\dmd.exe failed with exit code 1.
```

Still on Windows, If we replace `round` with `ceil`, we get `1 modules passed unittests`.
Whereas the original code on Linux `dub test -q` gives us `1 modules passed unittests`.

This is undocumented behaviour.

**Comment by hatf0** [comment]
This is not necessarily an issue with Mir, as we fall back to `std.math.round` which has this snippet:
https://github.com/dlang/phobos/blob/d08548e925e56ab283cff0626562c254d4ad459d/std/math/rounding.d#L732-L750

There is a subsequent unit-test showing that Linux/macOS are pure, but Windows is not:
https://github.com/dlang/phobos/blob/d08548e925e56ab283cff0626562c254d4ad459d/std/math/rounding.d#L761-L768
